### PR TITLE
Expose some of the missingness functions

### PR DESCRIPTION
**Pull request by pkoki**
Tables for clinical trials are very, very complete: typically n, mean, SD, median, IQR, range, missing, % missing are specified in the protocol. To keep the code readable I use convenience wrappers and some custom coding around describeMean and describeMedian. One needs to have access to the private functions prDescGetMissing and prConvertShowMissing. This pull request renames those functions to descGetMissing and convertShowMissing and exports them.

### CODE REVIEW

**Comment by gforge** [comment]
Thanks! Excellent job.

**Comment by lemna** [comment]
Hi Max!

are there any plans to integrate this into the CRAN version?

thanks
Peter.

**Comment by gforge** [comment]
@lemna I think this should be in the 1.4 version that I just pushed to CRAN. Correct me if I'm wrong.

**Comment by lemna** [comment]
I don't see any of this. I installed version 1.4 from CRAN:

> packageDescription('Gmisc')$Version
[1] "1.4"
> ?descGetMissing
No documentation for ‘descGetMissing’ in specified packages and libraries:
you could try ‘??descGetMissing’
> ?prDescGetMissing
> prDescGetMissing
Error: object 'prDescGetMissing' not found
> Gmisc::prDescGetMissing
Error: 'prDescGetMissing' is not an exported object from 'namespace:Gmisc'

**Comment by gforge** [comment]
Forgot to merge master into develop. Updated and re-submitted to CRAN with an apology.

**Comment by lemna** [comment]
Tack så mycket! ;-)

**Pull request merged**
